### PR TITLE
refactor TICC.ino.  Change Chan 0 to Chan A, and Chan 1 to Chan B.

### PR DESCRIPTION
**Pull request by Tom-McDermott**
TICC.ino: Re-label Chan 0 and 1 as Chan A and B.
 Eliminate duplicate subroutines, instead pass channel number as first parameter.
# include stdint.h in tdc_calc to define types, add dummy function name.

### CODE REVIEW

**Comment by mcdermj** [comment]
John and George --

Do you know how to deal with a pull request like this?  I’m happy to instruct if I have to.

> On Apr 17, 2016, at 3:27 PM, Tom McDermott, N5EG notifications@github.com wrote:
> 
> TICC.ino: Re-label Chan 0 and 1 as Chan A and B.
> Eliminate duplicate subroutines, instead pass channel number as first parameter.
> #include stdint.h in tdc_calc to define types, add dummy function name.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/TAPR/TICC/pull/1
> 
> Commit Summary
> 
>   • refactor TICC.ino. Change Chan 0 to Chan A, and Chan 1 to Chan B.
> File Changes
> 
>   • M TICC.ino (263)
>   • M tdc_calc_result.c (4)
> Patch Links:
> 
>   • https://github.com/TAPR/TICC/pull/1.patch
>   • https://github.com/TAPR/TICC/pull/1.diff
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub

## 

Jeremy McDermond (NH6Z)
Xenotropic Systems
mcdermj@xenotropic.com

**Comment by n8ur** [comment]
I think I figured it out.

**Comment by ghbyrkit** [comment]
```
Well, actually I wanted separate functions for each channel. No sense
```

in having to pass a channel ID when if you add more channels you have
to add more code anyway. I'm happy to have things changed from 0/1 to
A/B. But 'channel ID' only goes to a switch statement.

```
George

-----------------------------------------From: "John Ackermann N8UR" 
```

To: "TAPR/TICC"
Cc: 
Sent: Mon, 18 Apr 2016 08:11:23 -0700
Subject: Re: [TAPR/TICC] refactor TICC.ino. Change Chan 0 to Chan A,
and Chan 1 to Chan B. (#1)

 I think I figured it out.

 On 4/17/2016 9:09 PM, Jeremy McDermond wrote:

> John and George --
> 
> Do you know how to deal with a pull request like this? I’m happy
> to
> instruct if I have to.
> 
> > On Apr 17, 2016, at 3:27 PM, Tom McDermott, N5EG
> >  wrote:
> > 
> > TICC.ino: Re-label Chan 0 and 1 as Chan A and B.
> > Eliminate duplicate subroutines, instead pass channel number as
> > first
> > parameter.
> > #include stdint.h in tdc_calc to define types, add dummy function
> > name.
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/TAPR/TICC/pull/1 [1]
> > 
> > Commit Summary
> > 
> > • refactor TICC.ino. Change Chan 0 to Chan A, and Chan 1 to
> > Chan B.
> > File Changes
> > 
> > • M TICC.ino (263)
> > • M tdc_calc_result.c (4)
> > Patch Links:
> > 
> > • https://github.com/TAPR/TICC/pull/1.patch [2]
> > • https://github.com/TAPR/TICC/pull/1.diff [3]
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> 
> ## 
> 
> Jeremy McDermond (NH6Z)
> Xenotropic Systems
> mcdermj@xenotropic.com
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
>  [4]

```
—
```

 You are receiving this because you are subscribed to this thread.
 Reply to this email directly or view it on GitHub [5]     

## Links:

[1] https://github.com/TAPR/TICC/pull/1
[2] https://github.com/TAPR/TICC/pull/1.patch
[3] https://github.com/TAPR/TICC/pull/1.diff
[4] https://github.com/TAPR/TICC/pull/1#issuecomment-211144527>
[5] https://github.com/TAPR/TICC/pull/1#issuecomment-211422931

**Comment by Tom-McDermott** [comment]
Hi George,

The one thing I've always been hit on in code reviews is doing the same
thing in two places.
At some later point in time an update will get made, and one of the
routines will be changed
but not the other.  Having one routine means that even though code has to
be changed, it
only happens in one place.

-- Tom, N5EG

**Comment by mcdermj** [comment]
As a comment from the peanut gallery, if you’re using the copy/paste function 
in your editor, you should probably think really hard about whether you’re 
doing the right thing.

> On Apr 18, 2016, at 8:41 AM, Tom McDermott, N5EG notifications@github.com wrote:
> 
> Hi George,
> 
> The one thing I've always been hit on in code reviews is doing the same
> thing in two places.
> At some later point in time an update will get made, and one of the
> routines will be changed
> but not the other. Having one routine means that even though code has to
> be changed, it
> only happens in one place.
> 
> -- Tom, N5EG
> 
> On Mon, Apr 18, 2016 at 8:23 AM, George Byrkit notifications@github.com
> wrote:
> 
> > Well, actually I wanted separate functions for each channel. No sense
> > in having to pass a channel ID when if you add more channels you have
> > to add more code anyway. I'm happy to have things changed from 0/1 to
> > A/B. But 'channel ID' only goes to a switch statement.
> > 
> > George
> > 
> > -----------------------------------------From: "John Ackermann N8UR"
> > To: "TAPR/TICC"
> > Cc:
> > Sent: Mon, 18 Apr 2016 08:11:23 -0700
> > Subject: Re: [TAPR/TICC] refactor TICC.ino. Change Chan 0 to Chan A,
> > and Chan 1 to Chan B. (#1)
> > 
> > I think I figured it out.
> > 
> > On 4/17/2016 9:09 PM, Jeremy McDermond wrote:
> > 
> > > John and George --
> > > 
> > > Do you know how to deal with a pull request like this? I’m happy
> > > to
> > > instruct if I have to.
> > > 
> > > > On Apr 17, 2016, at 3:27 PM, Tom McDermott, N5EG
> > > > wrote:
> > > > 
> > > > TICC.ino: Re-label Chan 0 and 1 as Chan A and B.
> > > > Eliminate duplicate subroutines, instead pass channel number as
> > > > first
> > > > parameter.
> > > > #include stdint.h in tdc_calc to define types, add dummy function
> > > > name.
> > > > 
> > > > You can view, comment on, or merge this pull request online at:
> > > > 
> > > > https://github.com/TAPR/TICC/pull/1 [1]
> > > > 
> > > > Commit Summary
> > > > 
> > > > • refactor TICC.ino. Change Chan 0 to Chan A, and Chan 1 to
> > > > Chan B.
> > > > File Changes
> > > > 
> > > > • M TICC.ino (263)
> > > > • M tdc_calc_result.c (4)
> > > > Patch Links:
> > > > 
> > > > • https://github.com/TAPR/TICC/pull/1.patch [2]
> > > > • https://github.com/TAPR/TICC/pull/1.diff [3]
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly or view it on GitHub
> > > 
> > > ## 
> > > 
> > > Jeremy McDermond (NH6Z)
> > > Xenotropic Systems
> > > mcdermj@xenotropic.com
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > [4]
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub [5]
> > 
> > ## Links:
> > 
> > [1] https://github.com/TAPR/TICC/pull/1
> > [2] https://github.com/TAPR/TICC/pull/1.patch
> > [3] https://github.com/TAPR/TICC/pull/1.diff
> > [4] https://github.com/TAPR/TICC/pull/1#issuecomment-211144527>
> > [5] https://github.com/TAPR/TICC/pull/1#issuecomment-211422931
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/TAPR/TICC/pull/1#issuecomment-211429098
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub

## 

Jeremy McDermond (NH6Z)
Xenotropic Systems
mcdermj@xenotropic.com

**Comment by ghbyrkit** [comment]
```
Hi, Tom,

And I've been hit with the opposite: trying to combine 'apparently
```

similar' functionality when it involves invoking a switch/case
statement to handle the differences. So there are different practices
in different places that conflict. When you add that 'channel ID'
parameter, you then need to validate it, report and handle
out-of-domain values, etc. By not having the channelId parameter, I
avoided having to do those things.

```
I'm inclined to keep the renaming from 0/1 to A/B, as that is
```

something that John A and I agreed on, and to revert the other code as
being more performant without switch/case statements, parameter
validation, doing something sane in a 'default' case (if you have a
switch statement, you really need to handle the 'default' case...)

```
George

-----------------------------------------From: "Tom McDermott, N5EG" 
```

To: "TAPR/TICC"
Cc: "George Byrkit"
Sent: Mon, 18 Apr 2016 08:41:17 -0700
Subject: Re: [TAPR/TICC] refactor TICC.ino. Change Chan 0 to Chan A,
and Chan 1 to Chan B. (#1)

 Hi George,

 The one thing I've always been hit on in code reviews is doing the
same
 thing in two places.
 At some later point in time an update will get made, and one of the
 routines will be changed
 but not the other. Having one routine means that even though code has
to
 be changed, it
 only happens in one place.

 -- Tom, N5EG

 On Mon, Apr 18, 2016 at 8:23 AM, George Byrkit 
 wrote:

> Well, actually I wanted separate functions for each channel. No
> sense
> in having to pass a channel ID when if you add more channels you
> have
> to add more code anyway. I'm happy to have things changed from 0/1
> to
> A/B. But 'channel ID' only goes to a switch statement.
> 
> George
> 
> -----------------------------------------From: "John Ackermann
> N8UR"
> To: "TAPR/TICC"
> Cc:
> Sent: Mon, 18 Apr 2016 08:11:23 -0700
> Subject: Re: [TAPR/TICC] refactor TICC.ino. Change Chan 0 to Chan
> A,
> and Chan 1 to Chan B. (#1)
> 
> I think I figured it out.
> 
> On 4/17/2016 9:09 PM, Jeremy McDermond wrote:
> 
> > John and George --
> > 
> > Do you know how to deal with a pull request like this? I’m
> > happy
> > to
> > instruct if I have to.
> > 
> > > On Apr 17, 2016, at 3:27 PM, Tom McDermott, N5EG
> > > wrote:
> > > 
> > > TICC.ino: Re-label Chan 0 and 1 as Chan A and B.
> > > Eliminate duplicate subroutines, instead pass channel number as
> > > first
> > > parameter.
> > > #include stdint.h in tdc_calc to define types, add dummy
> > > function
> > > name.
> > > 
> > > You can view, comment on, or merge this pull request online at:
> > > 
> > > https://github.com/TAPR/TICC/pull/1 [1] [1]
> > > 
> > > Commit Summary
> > > 
> > > • refactor TICC.ino. Change Chan 0 to Chan A, and Chan 1 to
> > > Chan B.
> > > File Changes
> > > 
> > > • M TICC.ino (263)
> > > • M tdc_calc_result.c (4)
> > > Patch Links:
> > > 
> > > • https://github.com/TAPR/TICC/pull/1.patch [2] [2]
> > > • https://github.com/TAPR/TICC/pull/1.diff [3] [3]
> > > —
> > > You are receiving this because you are subscribed to this
> > > thread.
> > > Reply to this email directly or view it on GitHub
> > 
> > ## 
> > 
> > Jeremy McDermond (NH6Z)
> > Xenotropic Systems
> > mcdermj@xenotropic.com
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > [4]
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub [5]
> 
> ## Links:
> 
> [1] https://github.com/TAPR/TICC/pull/1 [4]
> [2] https://github.com/TAPR/TICC/pull/1.patch [5]
> [3] https://github.com/TAPR/TICC/pull/1.diff [6]
> [4] https://github.com/TAPR/TICC/pull/1#issuecomment-211144527> [7]
> [5] https://github.com/TAPR/TICC/pull/1#issuecomment-211422931 [8]
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
>  [9]

```
—
```

 You are receiving this because you commented.
 Reply to this email directly or view it on GitHub [10]     

## Links:

[1] https://github.com/TAPR/TICC/pull/1
[2] https://github.com/TAPR/TICC/pull/1.patch
[3] https://github.com/TAPR/TICC/pull/1.diff
[4] https://github.com/TAPR/TICC/pull/1
[5] https://github.com/TAPR/TICC/pull/1.patch
[6] https://github.com/TAPR/TICC/pull/1.diff
[7] https://github.com/TAPR/TICC/pull/1#issuecomment-211144527>
[8] https://github.com/TAPR/TICC/pull/1#issuecomment-211422931
[9] https://github.com/TAPR/TICC/pull/1#issuecomment-211429098>
[10] https://github.com/TAPR/TICC/pull/1#issuecomment-211437650

**Comment by Tom-McDermott** [comment]
Hi George,  multiple channels can also be handled by a structure. I expect
it unlikely that more than two channels would ever be implemented anyway.

You can revert the commit, but I don't have a version with only half the
commit (A/B only).

-- Tom, N5EG

**Comment by ghbyrkit** [comment]
```
Tom,

I had been waiting for working hardware before making the 0/1 -> A/B
```

changes. I think that the truth is somewhere in between our two
versions. For example, a function targeted to channel B can pass the
selector for channel B, rather than determine via an if or switch from
the channelId, and call a common function that has no if or switch.
More problematic is returning multiple values except via a global
variable, which is then stored according to the channel designator.

```
George

-----------------------------------------From: "Tom McDermott, N5EG" 
```

To: "TAPR/TICC"
Cc: "George Byrkit"
Sent: Mon, 18 Apr 2016 09:10:01 -0700
Subject: Re: [TAPR/TICC] refactor TICC.ino. Change Chan 0 to Chan A,
and Chan 1 to Chan B. (#1)

 Hi George, multiple channels can also be handled by a structure. I
expect
 it unlikely that more than two channels would ever be implemented
anyway.

 You can revert the commit, but I don't have a version with only half
the
 commit (A/B only).

 -- Tom, N5EG

 On Mon, Apr 18, 2016 at 8:59 AM, George Byrkit 
 wrote:

> Hi, Tom,
> 
> And I've been hit with the opposite: trying to combine 'apparently
> similar' functionality when it involves invoking a switch/case
> statement to handle the differences. So there are different
> practices
> in different places that conflict. When you add that 'channel ID'
> parameter, you then need to validate it, report and handle
> out-of-domain values, etc. By not having the channelId parameter, I
> avoided having to do those things.
> 
> I'm inclined to keep the renaming from 0/1 to A/B, as that is
> something that John A and I agreed on, and to revert the other code
> as
> being more performant without switch/case statements, parameter
> validation, doing something sane in a 'default' case (if you have a
> switch statement, you really need to handle the 'default' case...)
> 
> George
> 
> -----------------------------------------From: "Tom McDermott,
> N5EG"
> To: "TAPR/TICC"
> Cc: "George Byrkit"
> Sent: Mon, 18 Apr 2016 08:41:17 -0700
> Subject: Re: [TAPR/TICC] refactor TICC.ino. Change Chan 0 to Chan
> A,
> and Chan 1 to Chan B. (#1)
> 
> Hi George,
> 
> The one thing I've always been hit on in code reviews is doing the
> same
> thing in two places.
> At some later point in time an update will get made, and one of the
> routines will be changed
> but not the other. Having one routine means that even though code
> has
> to
> be changed, it
> only happens in one place.
> 
> -- Tom, N5EG
> 
> On Mon, Apr 18, 2016 at 8:23 AM, George Byrkit
> wrote:
> 
> > Well, actually I wanted separate functions for each channel. No
> > sense
> > in having to pass a channel ID when if you add more channels you
> > have
> > to add more code anyway. I'm happy to have things changed from
> > 0/1
> > to
> > A/B. But 'channel ID' only goes to a switch statement.
> > 
> > George
> > 
> > -----------------------------------------From: "John Ackermann
> > N8UR"
> > To: "TAPR/TICC"
> > Cc:
> > Sent: Mon, 18 Apr 2016 08:11:23 -0700
> > Subject: Re: [TAPR/TICC] refactor TICC.ino. Change Chan 0 to Chan
> > A,
> > and Chan 1 to Chan B. (#1)
> > 
> > I think I figured it out.
> > 
> > On 4/17/2016 9:09 PM, Jeremy McDermond wrote:
> > 
> > > John and George --
> > > 
> > > Do you know how to deal with a pull request like this? I’m
> > > happy
> > > to
> > > instruct if I have to.
> > > 
> > > > On Apr 17, 2016, at 3:27 PM, Tom McDermott, N5EG
> > > > wrote:
> > > > 
> > > > TICC.ino: Re-label Chan 0 and 1 as Chan A and B.
> > > > Eliminate duplicate subroutines, instead pass channel number
> > > > as
> > > > first
> > > > parameter.
> > > > #include stdint.h in tdc_calc to define types, add dummy
> > > > function
> > > > name.
> > > > 
> > > > You can view, comment on, or merge this pull request online
> > > > at:
> > > > 
> > > > https://github.com/TAPR/TICC/pull/1 [1] [1] [1]
> > > > 
> > > > Commit Summary
> > > > 
> > > > • refactor TICC.ino. Change Chan 0 to Chan A, and Chan 1 to
> > > > Chan B.
> > > > File Changes
> > > > 
> > > > • M TICC.ino (263)
> > > > • M tdc_calc_result.c (4)
> > > > Patch Links:
> > > > 
> > > > • https://github.com/TAPR/TICC/pull/1.patch [2] [2] [2]
> > > > • https://github.com/TAPR/TICC/pull/1.diff [3] [3] [3]
> > > > —
> > > > You are receiving this because you are subscribed to this
> > > > thread.
> > > > Reply to this email directly or view it on GitHub
> > > 
> > > ## 
> > > 
> > > Jeremy McDermond (NH6Z)
> > > Xenotropic Systems
> > > mcdermj@xenotropic.com
> > > 
> > > —
> > > You are receiving this because you are subscribed to this
> > > thread.
> > > Reply to this email directly or view it on GitHub
> > > [4]
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub [5]
> > 
> > ## Links:
> > 
> > [1] https://github.com/TAPR/TICC/pull/1 [4] [4]
> > [2] https://github.com/TAPR/TICC/pull/1.patch [5] [5]
> > [3] https://github.com/TAPR/TICC/pull/1.diff [6] [6]
> > [4] https://github.com/TAPR/TICC/pull/1#issuecomment-211144527>
> > [7] [7]
> > [5] https://github.com/TAPR/TICC/pull/1#issuecomment-211422931
> > [8] [8]
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > [9]
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub [10]
> 
> ## Links:
> 
> [1] https://github.com/TAPR/TICC/pull/1 [9]
> [2] https://github.com/TAPR/TICC/pull/1.patch [10]
> [3] https://github.com/TAPR/TICC/pull/1.diff [11]
> [4] https://github.com/TAPR/TICC/pull/1 [12]
> [5] https://github.com/TAPR/TICC/pull/1.patch [13]
> [6] https://github.com/TAPR/TICC/pull/1.diff [14]
> [7] https://github.com/TAPR/TICC/pull/1#issuecomment-211144527>
> [15]
> [8] https://github.com/TAPR/TICC/pull/1#issuecomment-211422931 [16]
> [9] https://github.com/TAPR/TICC/pull/1#issuecomment-211429098>
> [17]
> [10] https://github.com/TAPR/TICC/pull/1#issuecomment-211437650
> [18]
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
>  [19]

```
—
```

 You are receiving this because you commented.
 Reply to this email directly or view it on GitHub [20]     

## Links:

[1] https://github.com/TAPR/TICC/pull/1
[2] https://github.com/TAPR/TICC/pull/1.patch
[3] https://github.com/TAPR/TICC/pull/1.diff
[4] https://github.com/TAPR/TICC/pull/1
[5] https://github.com/TAPR/TICC/pull/1.patch
[6] https://github.com/TAPR/TICC/pull/1.diff
[7] https://github.com/TAPR/TICC/pull/1#issuecomment-211144527>
[8] https://github.com/TAPR/TICC/pull/1#issuecomment-211422931
[9] https://github.com/TAPR/TICC/pull/1
[10] https://github.com/TAPR/TICC/pull/1.patch
[11] https://github.com/TAPR/TICC/pull/1.diff
[12] https://github.com/TAPR/TICC/pull/1
[13] https://github.com/TAPR/TICC/pull/1.patch
[14] https://github.com/TAPR/TICC/pull/1.diff
[15] https://github.com/TAPR/TICC/pull/1#issuecomment-211144527>
[16] https://github.com/TAPR/TICC/pull/1#issuecomment-211422931
[17] https://github.com/TAPR/TICC/pull/1#issuecomment-211429098>
[18] https://github.com/TAPR/TICC/pull/1#issuecomment-211437650
[19] https://github.com/TAPR/TICC/pull/1#issuecomment-211445515>
[20] https://github.com/TAPR/TICC/pull/1#issuecomment-211448984

**Comment by n8ur** [comment]
Gee, now I know how Linus Torvalds feels. :-)  I'll just thank you both 
for contributing!

Seriously, I think there is a possibility of the project expanding to 
support a 4 or more channel version.  There's no reason you couldn't 
stack boards (with only minor hardware changes) to add additional pairs 
of input channels.

So that might weigh in favor taking the channel as a parameter.  But I'm 
by far the least expert coder in this group...

## John

**Pull request merged**
