### PR TITLE
Add platformio.ini to enable building with PlatformIO

### PR DESCRIPTION
**Pull request by arodland**
PlatformIO (platformio.org) is a pretty nice alternative to the Arduino IDE, supporting a commandline mode as well as an Atom-based editor. TICC builds with it without any changes if this config file is provided, so I thought it might be nice to support. PlatformIO also doesn't require any additional "installation" step for the EnableInterrupts library.

### CODE REVIEW

**Comment by n8ur** [comment]
Thanks, Andrew!  I'll get this added -- I presume it should go into the 
"TICC" source directory?

John
----

**Comment by arodland** [comment]
No, it's good as it is. It can be moved into the TICC directory, but the following changes would have to be made:

* change `src_dir = TICC` to `src_dir = .`
* change `lib_deps = file://./EnableInterrupt.zip` to `lib_deps = file://../EnableInterrupt.Zip`

I think it's most convenient at the top level, but I can see the sense of moving it down to avoid confusion with any other buildables that might be in the repo.

**Comment by n8ur** [comment]
I think I will move it down, as there are a couple of other sketches one 
might get to in the repo.  I'll make the changes below when I do.  Thanks!

**Comment by n8ur** [comment]
OK, it's been added in ./TICC with the changes below.  Thanks!

John
----

**Pull request closed without merging**
