### PR TITLE
RefClk drives EXT_LED_3

### PR DESCRIPTION
**Pull request by Curt-T**
LED indication of the presence of the reference clock input:

Routine added to loop() that checks for increments on PICcount, If present then EXT_LED_C on pin A11 is asserted. If increments are not present, the LED is extinguished. Testing showed no noticeable effect on measurement speed.

### CODE REVIEW

**Comment by n8ur** [comment]
Curt, I'm implementing this via cut-and-paste due to some other changes I made to LED handling.  But question: doesn't the test for (2.5 * PICTICK_PS / 1000000) drag in floating point, which is otherwise completely avoided in the code?

**Comment by Curt-T** [comment]
John, you are right – the test should be changed to a hard-coded number (=250).

I thought that PICKTICK_PS was a constant, so that the expression (2.5 * PICTICK_PS/1000000) would be reduced to a constant by the compiler.  But of course PICTICK_PS is in fact an int64_t variable, so the expression would have to be evaluated at run time. That was an oversight on my part.

The only drawback to a hard-coded number is that it will not track a change in the Coarse Clock Rate, should the user configure something significantly different from the default value. In principle, we could compute (2.5 * PICTICK_PS/1000000) in the setup() code, assign it to a variable, and pass that to the loop. That would allow changes in configuration to ripple through.

But since changing the Coarse Clock Rate would pretty much break the rest of the firmware, I think we are safe with hard-coding the constant that corresponds to the default rate :-)

**Comment by n8ur** [comment]
OK, code is implemented and tested (via DMM on A11) using hard-coded 
value.  Seems to do the trick; thanks!

John
----

**Comment by n8ur** [comment]
Change made via cut and paste into master, with tweaks to avoid use of floating point, and to use macro for faster LED handling.

**Pull request closed without merging**
